### ISSUE TITLE
permission to fork

### ISSUE THREAD

**Issue by JaredWeakStrike** [MarvinXLII/OT2R#1]
I would like to fork this repo and use it for a multiworld randomizer of ot2. 

Ideally this repo would be under the mit license for my uses since I can have it in its own repo. I would still give you massive credit for making this.

**Comment by emcleary** [comment]
Thanks for the interest, but I have to refuse this. I see OT2R as a personal project of mine that I still love and am actively working on (despite what the activity may suggest). Seeing it be reused elsewhere won't sit right with me.

**Comment by MarvinXLII** [comment]
Thanks for the interest, but I have to refuse this. I see OT2R as a personal project of mine that I still love and am actively working on (despite what the activity may suggest). Seeing it be reused elsewhere won't sit right with me.

**Comment by JaredWeakStrike** [comment]
That's totally understandable and I really respect that. Thanks for getting back to me!
