### ISSUE TITLE
Is it possible to shuffle/randomize the music of Octopath Traveler 2?

### ISSUE THREAD

**Issue by JubejuofGrimsby** [MarvinXLII/OT2R#2]
Dear MarvinXLII,
I'm a VGM composer and a fan of your randomizer. My friends and I really enjoy the laughs it gave us. I'm messaging you through the GitHub account I just made to ask a simple question: Would it be possible to shuffle/randomize every single song in Octopath 2? For example, if I am traversing Wellgrove, there'd be chance I start hearing a different area theme like Winterbloom, a battle theme like Normal Battle 3, or even a song only used in cutscenes like A Verdant Wind Blows or Partitio the Merchant. The jingles can be left alone, but every other song in the game, including night time themes, could be randomized. I'd be curious to see how this could work and if have any further questions, feel free to reply here or send me an email at nchammer122@gmail.com to discuss logistics. Thanks again for your randomizers and I hope to hear from you soon!

Sincerely,

Jubeju of Grimsby

**Comment by MarvinXLII** [comment]
Hey, thanks for the interest. I took a look at shuffling around music, but a major issue I see with it is getting volume right. Volumes seem to vary between different places, battles, and cutscenes. I think getting volume right is really important both for enjoyment and safety reasons, and I see no easy way to do that. If I ever stumble upon an easy way to get volume right I'll let you know, but for now let's assume that that won't happen.

**Comment by JubejuofGrimsby** [comment]
Hey, thanks for getting back to me! I understand what you mean, it does make sense from a game design standpoint. Please do keep in the loop if you find a way to have the mixed volume level attached to the songs or another way to carry the parameters over. If you do, I'd be more than happy to help you mix them to levels that closely match the originals! Thanks again and can't wait to see what you shuffle next!
