### ISSUE TITLE
"Randomizer" text doesn't appear on the title screen, other options seem to work.

### ISSUE THREAD

**Issue by kamooey** [MarvinXLII/OT2R#3]
I tried two different seeds and the title screen doesn't show any indication of being randomized (unless I'm mistaken on where I should be looking), but the randomizer itself works after starting a new game. I didn't play very far, but skills have been randomized correctly, and the formation button was enabled in the menu. 
![octo1](https://github.com/MarvinXLII/OT2R/assets/86388833/deebe61c-7344-414d-b41c-3206f0931dd6)
![octo2](https://github.com/MarvinXLII/OT2R/assets/86388833/1bc46981-fa5c-48b3-b465-ca4b5cfc1432)

This is randomizer version 0-4-3

**Comment by MarvinXLII** [comment]
I haven't had any issues with it, and I don't have any ideas how patching the image could get skipped. If you're willing to share your settings.json file I can try to replicate it myself.

**Comment by kamooey** [comment]
For more context, it's on whatever current game version there is.
I don't have any other mods installed, I used Special K last time I played but it wasn't running when I loaded the randomizer.
[settings.json](https://github.com/MarvinXLII/OT2R/files/13288930/settings.json)

**Comment by MarvinXLII** [comment]
Ok, I think I figured it out. I knew there were 3 copies of the main screen, but I thought they were for different devices (e.g. PC, Switch). Instead they actually correspond to texture resolutions in the in game settings (Low, Medium, High). The rando only modifies the image for the High setting. Turn your setting back to High and the modded image should be visible again (see Settings > Graphics Options > UI Texture Resolution).

Thanks for bringing this to my attention. I'll patch the other images when I get a chance.

**Comment by kamooey** [comment]
Works now! Glad it was something simple o7
![octo3](https://github.com/MarvinXLII/OT2R/assets/86388833/f8acf9a6-1163-43bd-a3b4-78eba1413d20)
