### ISSUE TITLE
"The flashback won't work here. Just skip it."

### ISSUE THREAD

**Issue by Pronyo-Chan** [MarvinXLII/OT2R#4]
Hi! I'm trying out the new event shuffle features where I'm shuffling PCs in the item pool and noticed something weird when recruiting my first party member.

I started with Agnea and went to recruit Partitio. After talking to him, I got a prompt saying "The flashback won't work here. Just skip it.". Choosing "Yes" just prompts the choice infinitely until I pick "No". Everything seems fine after picking "No".
I'm not sure what's the intent here, but from my point of view it feels like the choices are inverted because "No" actually skipped the event, and it probably shouldn't be a choice at all if the flashback won't work?

It's a very minor thing but I thought I should report it. Thank you for this amazing randomizer by the way, I had a blast playing it earlier this year and it's looking better than ever now with the recent added features!

**Comment by MarvinXLII** [comment]
The original text is "Hear the beginning of X's tale?", where the answer choices default to "No". Maybe I should just append the original text than replace it. Either way, I'll close this issue for now since it's so minor.

Thanks for playing!
