### ISSUE TITLE
gate of finis door not open

### ISSUE THREAD

**Issue by ndass33** [MarvinXLII/OT2R#6]
i was doing main story key randomizer
and after doing all prerequisite quest and reigniting all the flames, also doing the vidania
but when i go to gate of finis the door wasnt even there
i dont have any story progression anymore, and i already done all the checks i need

so maybe this is a bug or something ? i dont know
probably you can check into this issue ?
thank you

**Comment by MarvinXLII** [comment]
Thanks for playing and for the feedback. Be aware that the rando wasn't really designed to do anything postgame, so I'm not too surprised if there are issues like this. I think there were, and may still be, issues with the Epilogue, for example.

Can you confirm that the Gate of Finis worked before doing extinguishing the flames?

Also, please share the "settings.json" file from your seed, if you can. That helps document exactly which settings you used.

**Comment by ndass33** [comment]
i have finished 1 run with post vidania (i always use gate between world quest for ending the run)
and the gate was there, but i think i finished the quest in library after vidania
my latest run all 3 quest were before vidania.

also few run with main story, but without sacred flame option ticked in the rando setting
and this never had any problem


[settings.json](https://github.com/MarvinXLII/OT2R/files/15419009/settings.json)
is this how i attach file? hope this work

**Comment by MarvinXLII** [comment]
It took some time to track down the issue, but it ended up being a bug recruiting PCs and setting appropriate flags for galdera (the 8 PC check). I'm amazed neither I nor speedrunners have stumbled upon this bug by now. Thanks for bringing it to my attention.

It's fixed in the v0.5.2 release.
